"""initial

Revision ID: 34c2f045c2af
Revises: 
Create Date: 2023-08-08 13:42:02.836859

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '34c2f045c2af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
