"""init

Revision ID: 812f86587863
Revises: 
Create Date: 2023-08-04 11:39:15.536723

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '812f86587863'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
