"""task status edited

Revision ID: bd07c793f915
Revises: d33f2c552690
Create Date: 2023-08-09 13:52:29.946222

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd07c793f915'
down_revision = 'd33f2c552690'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
