"""initial

Revision ID: c35332555d34
Revises: 34c2f045c2af
Create Date: 2023-08-08 13:42:27.503661

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c35332555d34'
down_revision = '34c2f045c2af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
