"""edit user

Revision ID: d33f2c552690
Revises: ed5b75c2346b
Create Date: 2023-08-08 13:51:43.391095

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd33f2c552690'
down_revision = 'ed5b75c2346b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType([('Admin', 'Admin'), ('User', 'User')]), nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
